
# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://www.jinhuiqian.top:3306/bilibili?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: laishuxia
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: top.flobby.tools.entity


minio:
  endpoint: http://106.14.246.27:9050
  accessKey: FLOBBY
  secretKey: FlobbYKobeBryAnt