### 测试环境
server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:~/test
    username: root
    password: kobe24
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console